=== Fha2713/xml-lab/bow_ranking.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT bow-ranking (club, person, tournament)>

<!ELEMENT club (club-name, archer, trainer)>
<!ELEMENT club-name (#PCDATA)>
<!ELEMENT archer (#PCDATA)>
<!ELEMENT trainer (#PCDATA)>


<!ELEMENT person (firstname+, lastname+, gender+, year-of-birth, age-group, statistic)>
<!ATTLIST person
    id CDATA #REQUIRED>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT year-of-birth (#PCDATA)>
<!ELEMENT age-group (#PCDATA)>


<!ELEMENT statistic (shooting-styles+, shooting-accuracy, total-points)>

<!ELEMENT shooting-styles (#PCDATA)>

<!ELEMENT shooting-accuracy (#PCDATA)>

<!ELEMENT total-points (#PCDATA)>


<!ELEMENT tournament (ranking)>
<!ATTLIST tournament
    name CDATA #REQUIRED>
<!ELEMENT ranking EMPTY>
<!ATTLIST ranking
    rank CDATA #REQUIRED
    archer-id CDATA #REQUIRED
    points CDATA #REQUIRED>

=== Fha2713/xml-lab/bow_ranking.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bow-ranking SYSTEM "bow_ranking.dtd">
<?xml-stylesheet type="text/xsl" href="bow_ranking.xsl"?>
<bow-ranking edition="2024-Q1">
	<club>
		<club-name>BSC Hohenems</club-name>
		<archer person-id="p0"/>
		<archer person-id="p1"/>
		<archer person-id="p2"/>
		<archer person-id="p3"/>
		<archer person-id="p4"/>
		<archer person-id="p5"/>
		<trainer person-id="p6"/>
	</club>
	<club>
		<club-name>BSC Lustenau</club-name>
		<archer  person-id="p6"/>
		<archer person-id="p7"/>
		<archer person-id="p8"/>
		<archer person-id="p9"/>
		<archer person-id="p10"/>
		<archer person-id="p11"/>
		<trainer person-id="p1"/>
	</club>
	<club>
		<club-name>BSC Dornbirn</club-name>
		<archer person-id="p12"/>
		<archer person-id="p13"/>
		<archer person-id="p14"/>
		<archer person-id="p15"/>
		<archer person-id="p16"/>
		<archer person-id="p17"/>
		<trainer person-id="p18"/>
	</club>
	<club>
		<club-name>BSC Götzis</club-name>
		<archer person-id="p18"/>
		<archer person-id="p19"/>
		<archer person-id="p20"/>
		<archer person-id="p21"/>
		<archer person-id="p22"/>
		<archer person-id="p23"/>
		<trainer person-id="p12"/>
	</club>
	
	<person id="p0">
		<firstname>Michelle</firstname>
		<lastname>Bader</lastname>
		<gender>f</gender>
		<year-of-birth>2000</year-of-birth>
		<age-group>U60</age-group>
    	<statistic>
        	<shooting-styles>Freestyle unlimited (FU)</shooting-styles>
        	<shooting-accuracy>89%</shooting-accuracy>
        	<total-points>990</total-points>
    	</statistic>
	</person>
	<person id="p1">
		<firstname>Wade</firstname>
		<lastname>Wilson</lastname>
		<gender>m</gender>
		<year-of-birth>1976</year-of-birth>
		<age-group>U60</age-group>
		<statistic>
        	<shooting-styles>Bowhunter recurve and compound (BH)</shooting-styles>
        	<shooting-accuracy>75%</shooting-accuracy>
        	<total-points>780</total-points>
    	</statistic>
	</person>
	<person id="p2">
		<firstname>Thor</firstname>
		<lastname>Odinson</lastname>
		<gender>m</gender>
		<year-of-birth>1983</year-of-birth>
		<age-group>U60</age-group>
		<statistic>
        	<shooting-styles>Bowhunter limited (BL)</shooting-styles>
        	<shooting-accuracy>62%</shooting-accuracy>
        	<total-points>650</total-points>
    	</statistic>
	</person>
	<person id="p3">
		<firstname>Bruce</firstname>
		<lastname>Banner</lastname>
		<gender>m</gender>
		<year-of-birth>1968</year-of-birth>
		<age-group>U60</age-group>
		<statistic>
        	<shooting-styles>Historical Bow (HB) and Traditional Recurve Bow (TR)</shooting-styles>
        	<shooting-accuracy>80%</shooting-accuracy>
        	<total-points>780</total-points>
    	</statistic>
	</person>
	<person id="p4">
		<firstname>Peter</firstname>
		<lastname>Quill</lastname>
		<gender>m</gender>
		<year-of-birth>1979</year-of-birth>
		<age-group>U60</age-group>
		<statistic>
        	<shooting-styles>Longbow (LB)</shooting-styles>
        	<shooting-accuracy>57%</shooting-accuracy>
        	<total-points>660</total-points>
    	</statistic>
	</person>
	<person id="p5">
		<firstname>Eddie</firstname>
		<lastname>Brock</lastname>
		<gender>m</gender>
		<year-of-birth>1977</year-of-birth>
		<age-group>U60</age-group>
		<statistic>
        	<shooting-styles>Freestyle limited recurve and compound (FS)</shooting-styles>
        	<shooting-accuracy>83%</shooting-accuracy>
        	<total-points>790</total-points>
    	</statistic>
	</person>
	<person id="p6">
        <firstname>Mario</firstname>
        <lastname>Haberfellner</lastname>
        <gender>m</gender>
        <year-of-birth>2003</year-of-birth>
        <age-group>U21</age-group>
        <statistic>
            <shooting-styles>Bowhunter recurve and compound (BH)</shooting-styles>
            <shooting-accuracy>85%</shooting-accuracy>
            <total-points>820</total-points>
        </statistic>
    </person>
    <person id="p7">
        <firstname>Mendrit</firstname>
        <lastname>Hoti</lastname>
        <gender>m</gender>
        <year-of-birth>2004</year-of-birth>
        <age-group>U21</age-group>
        <statistic>
            <shooting-styles>Longbow (LB)</shooting-styles>
            <shooting-accuracy>86%</shooting-accuracy>
            <total-points>830</total-points>
        </statistic>
    </person>
    <person id="p8">
        <firstname>Paul</firstname>
        <lastname>Ortner</lastname>
        <gender>m</gender>
        <year-of-birth>2004</year-of-birth>
        <age-group>U21</age-group>
        <statistic>
            <shooting-styles>Historical Bow (HB)</shooting-styles>
            <shooting-accuracy>77%</shooting-accuracy>
            <total-points>750</total-points>
        </statistic>
    </person>
    <person id="p9">
        <firstname>Sven</firstname>
        <lastname>Den Uijl</lastname>
        <gender>m</gender>
        <year-of-birth>2002</year-of-birth>
        <age-group>U60</age-group>
        <statistic>
            <shooting-styles>Freestyle limited recurve and compound (FS)</shooting-styles>
            <shooting-accuracy>91%</shooting-accuracy>
            <total-points>930</total-points>
        </statistic>
    </person>
    <person id="p10">
        <firstname>Paul</firstname>
        <lastname>Hagenbucher</lastname>
        <gender>m</gender>
        <year-of-birth>2004</year-of-birth>
        <age-group>U21</age-group>
        <statistic>
            <shooting-styles>Freestyle limited recurve and compound (FS)</shooting-styles>
            <shooting-accuracy>82%</shooting-accuracy>
            <total-points>790</total-points>
        </statistic>
    </person>
    <person id="p11">
        <firstname>Christopher</firstname>
        <lastname>Wolf</lastname>
        <gender>m</gender>
        <year-of-birth>2004</year-of-birth>
        <age-group>U21</age-group>
        <statistic>
            <shooting-styles>Barebow recurve and compound (BB)</shooting-styles>
            <shooting-accuracy>90%</shooting-accuracy>
            <total-points>900</total-points>
        </statistic>
	</person>
	<person id="p12">
        <firstname>Thomas</firstname>
        <lastname>Müller</lastname>
        <gender>m</gender>
        <year-of-birth>1989</year-of-birth>
        <age-group>U60</age-group>
        <statistic>
            <shooting-styles>Traditional Recurve Bow (TR)</shooting-styles>
            <shooting-accuracy>85%</shooting-accuracy>
            <total-points>943</total-points>
        </statistic>
    </person>
    <person id="p13">
        <firstname>Harry</firstname>
        <lastname>Kane</lastname>
        <gender>m</gender>
        <year-of-birth>1994</year-of-birth>
        <age-group>U60</age-group>
        <statistic>
            <shooting-styles>Historical Bow (HB) </shooting-styles>
            <shooting-accuracy>92</shooting-accuracy>
            <total-points>950</total-points>
        </statistic>
    </person>
    <person id="p14">
        <firstname>Manuel</firstname>
        <lastname>Neuer</lastname>
        <gender>m</gender>
        <year-of-birth>1986</year-of-birth>
        <age-group>U60</age-group>
        <statistic>
            <shooting-styles>Bowhunter limited (BL)</shooting-styles>
            <shooting-accuracy>70%</shooting-accuracy>
            <total-points>680</total-points>
        </statistic>
    </person>
    <person id="p15">
        <firstname>Joshua</firstname>
        <lastname>Kimmich</lastname>
        <gender>m</gender>
        <year-of-birth>1995</year-of-birth>
        <age-group>U60</age-group>
        <statistic>
            <shooting-styles>Longbow (LB)</shooting-styles>
            <shooting-accuracy>97%</shooting-accuracy>
            <total-points>990</total-points>
        </statistic>
    </person>
    <person id="p16">
        <firstname>Tobias</firstname>
        <lastname>Herburger</lastname>
        <gender>m</gender>
        <year-of-birth>2004</year-of-birth>
        <age-group>U21</age-group>
        <statistic>
            <shooting-styles>Bowhunter unlimited (BU)</shooting-styles>
            <shooting-accuracy>85%</shooting-accuracy>
            <total-points>890</total-points>
        </statistic>
    </person>
    <person id="p17">
        <firstname>Paul</firstname>
        <lastname>Herburger</lastname>
        <gender>m</gender>
        <year-of-birth>2006</year-of-birth>
        <age-group>U21</age-group>
        <statistic>
            <shooting-styles>Bowhunter recurve und compound (BH)</shooting-styles>
            <shooting-accuracy>90%</shooting-accuracy>
            <total-points>912</total-points>
        </statistic>
    </person>
    <person id="p18">
        <firstname>Katharina</firstname>
        <lastname>Herburger</lastname>
        <gender>f</gender>
        <year-of-birth>2000</year-of-birth>
        <age-group>U60</age-group>
        <statistic>
            <shooting-styles>Freestyle unlimited (FU)</shooting-styles>
            <shooting-accuracy>88%</shooting-accuracy>
            <total-points>890</total-points>
        </statistic>
    </person>
   	<person id="p19">
        <firstname>Alex</firstname>
        <lastname>Morgan</lastname>
        <gender>f</gender>
        <year-of-birth>1989</year-of-birth>
        <age-group>U60</age-group>
        <statistic>
            <shooting-styles>Bowhunter unlimited (BU)</shooting-styles>
            <shooting-accuracy>54%</shooting-accuracy>
            <total-points>666</total-points>
        </statistic>
    </person>
    <person id="p20">
        <firstname>Lena</firstname>
        <lastname>Oberdorf</lastname>
        <gender>f</gender>
        <year-of-birth>2001</year-of-birth>
        <age-group>U60</age-group>
        <statistic>
            <shooting-styles>Longbow (LB) </shooting-styles>
            <shooting-accuracy>79%</shooting-accuracy>
            <total-points>777</total-points>
        </statistic>
    </person>
    <person id="p21">
        <firstname>Jule</firstname>
